require 'date'
require 'optparse'
require './src/schema_converter'

params = ARGV.getopts('s:o:n:')

INPUT_FILE = params["s"]
OUT_FILE = params["o"]
NAME_SPACE = params["n"]

$convert_types = []
$schema_version = ''

def create_table(table_name, *arg, &block)
  converter = SchemaConverter.new(table_name: table_name)
  block.call(converter)
  converter.finalize

  $convert_types.concat(converter.out_text)
end

module ActiveRecord
  class Schema
    def self.define(version, &block)
      $schema_version = version[:version]
      block.call
    end
  end
end

eval(File.read(INPUT_FILE))

name_space = NAME_SPACE ? NAME_SPACE : "schema"
convert_type_text =
    $convert_types.map { |t| "  #{t}" }.join("\n").strip

File.open(OUT_FILE, "w") do |f|
  CONVERT_TEXT = <<-EOS
/* eslint no-unused-vars: 0 */

/**
 * auto-generated file @#{Date.today.to_time}
 * schema version: #{$schema_version}
 * This file was automatically generated by schema2type
 */
declare namespace #{name_space} {
  #{convert_type_text}
}
  EOS
  f.puts CONVERT_TEXT
end


