require 'date'

module Schema2type

  $convert_types = []
  $schema_version = ''

  def self.execute(input_file:, out_file:, name_space: "schema")

    eval(File.read(input_file))

    convert_type_text = $convert_types.map { |t| "  #{t}" }.join("\n").strip

    File.open(out_file, "w") do |f|
    f.puts <<-EOS
/* eslint no-unused-vars: 0 */

/**
 * auto-generated file @#{Date.today.to_time}
 * schema version: #{$schema_version}
 * This file was automatically generated by schema2type
 */
declare namespace #{name_space} {
  #{convert_type_text}
}
      EOS
    end
  end

  private

  def self.create_table(table_name, *arg, &block)
    converter = SchemaConverter.new(table_name: table_name)
    block.call(converter)
    converter.finalize

    $convert_types.concat(converter.out_text)
  end

  module ActiveRecord
    class Schema
      def self.define(version, &block)
        $schema_version = version[:version]
        block.call
      end
    end
  end
end
